"""Adding role column to users

Revision ID: d357fb71b73d
Revises: 63e38953acff
Create Date: 2023-11-21 01:19:28.884704

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d357fb71b73d"
down_revision: Union[str, None] = "63e38953acff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("authene_user", sa.Column("role", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("authene_user", "role")
    # ### end Alembic commands ###
